# Sumit Das 2016 09 15
# Read AllSID list

#set -x

ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbva101c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  civa101.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdgx66c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidgx66.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbsgx74c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cisgx74.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdgh12c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidgh12.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgdt24c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigdt24.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbagh58c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciagh58.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdnu26c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidnu26.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jddn227c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jidn227.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgqt22c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigqt22.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidge10.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cisge11.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbsge11c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdge10c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs9e32c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis9e32.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis1e33.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs1e33c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbqnu23c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciqnu23.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdqn224c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jiqn224.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs2e63c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis2e63.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs8e25c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis8e25.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs6e23c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis6e23.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs7e26c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis7e26.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cia9e79.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dba9e79c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cia1e81.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dba1e81c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbm2e29c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cim2e29.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbmgb13c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidgu49.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdgu49c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cimgb13.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  lcdgl86.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis9b14.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs9b14c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  citge15.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbtge15c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs8b54c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis8b54.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis1b73.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs1b73c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbagu20c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciagu20.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgq828c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigq828.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbscb97c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciscb97.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgd818c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigd818.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbsgu48c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cisgu48.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbbwd71c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cibwd71.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgdb53c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigdb53.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgdu65c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigdu65.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbzd256c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgqb63c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigqb63.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cizd256.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgda50c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigda50.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbbwq72c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cibwq72.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbzq266c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cizq266.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigdf27.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdgdf27c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigdl11.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdgdl11c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbpfe07c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cipfe07.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigqf30.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigqf31.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdgqf30c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbagb76c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciagb76.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdpd136c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jipd136.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdjgb59c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jijgb59.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbage02c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciage02.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbhqs21c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cihqs21.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jijmg41.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdjmg41c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigql19.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigql20.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdgql19c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdscj44c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jiscj44.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdgrl15c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigrl15.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdpt134c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jipt134.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs0225c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis0225.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgqa60c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigqa60.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbd0328c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cid0328.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbhps22c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cihps22.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbt0327c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cit0327.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbsge11c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cisge11.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs9e32c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis9e32.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs2e63c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis2e63.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbs1e33c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cis1e33.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbqnu23c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciqnu23.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jiqn224.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdqn224c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgqt22c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigqt22.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgdt24c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigdt24.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdnu26c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidnu26.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jidn227.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jddn227c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdgh12c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidgh12.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdge10c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidge10.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbagh58c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciagh58.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdsidsnc.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jipgd04.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbpgx32c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cipgx32.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdpgd04c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdjd111c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jijq121.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdjq121c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jijm141.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdjm141c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jijd418.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdjd418c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jijd111.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbvx472c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  civx472.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbvq120c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  civq120.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbvm140c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  civm140.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbvd408c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  civd408.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbvd110c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  civd110.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cidd156.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbdd156c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jipgi07.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdpgi07c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbpgh59c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cipgh59.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbpnu42c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cipnu42.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jipn243.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdpn243c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgpt20c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigpt20.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip7e46.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp7e46c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip9e24.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp9e24c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app9e67.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app9e68.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app9e12.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app9e27.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp8e47c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip8e47.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app8e13.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app8e31.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp6e45c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip6e45.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdgcu87c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigcu87.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbpgu83c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cipgu83.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbprd00c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  ciprd00.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  apprd42.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  apprd41.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  apprd43.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  apprd44.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgd818c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigd818.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgp848c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigp848.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbzp286c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cizp286.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp2e69c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip2e69.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app2e77.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  app2e70.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp9b19c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip9b19.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp8b55c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip8b55.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbbwp70c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cibwp70.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbpgv80c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cipgv80.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbp1b37c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbpcb98c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cipcb98.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cip1b37.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigpf34.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jigpf35.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  jdgpf34c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  citpf36.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  dbgpb61c.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh
ssh -q -o connecttimeout=10 -o batchmode=yes -o stricthostkeychecking=no  cigpb61.edc.linde.grp ~/moni/readDCPAIXlist4ssh2.sh

